# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  # Tu configuración existente para "uv"
  #- package-ecosystem: "uv"
  #  directory: "/"
  #  schedule:
  #    interval: "weekly"
  #  open-pull-requests-limit: 10

  # La configuración de "python" que agregamos
  - package-ecosystem: "python"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
